import React from "react";
import BrandLink from "../components/BrandLink/BrandLink";
import FactNumber from "../components/FactNumber";

const About = () => {
  return (
    <>
      <div className="flex items-center">
        <div className="relative my-20  mx-auto ">
          <div className="absolute bg-yellow h-14 rounded-full top-0 w-14 -z-1"></div>
          <BrandLink classes="text-6xl ml-5" />
        </div>
      </div>

      <div className=" py-10  text-justify  ">
        <div className="mx-auto w-2/3 ">
          <p className=" mb-4">
            Welly is the leading premium beauty platform in Europe. Offering
            more than 130,000 beauty and lifestyle products in online shops, the
            beauty marketplace and more than 2,000 stores, Welly inspires
            customers to live their own kind of beauty by a previously
            unparalleled assortment.
          </p>
          <p>
            The continued expansion of the fast-growing e‑commerce business is
            the focus of the
            <span className="font-krona"> #forwardbeauty</span>. DigitalFirst
            strategy programme. In fiscal year 2019/2020, Welly generated sales
            of 3.2 billion euros in the areas of perfumery, decorative
            cosmetics, skin and hair care as well as nutritional supplements and
            accessories.
            <span className="font-krona"> #letsdobeautiful</span>
          </p>
        </div>
      </div>
      <div className="bg-yellow">
        <div className="flex flex-col md:flex-row md:space-y-0 space-y-10 py-10  space-x-4 w-3/4 mx-auto">
          {/* Facts And Figures */}
          <FactNumber
            icon={"people"}
            number="20,000"
            title="Beauty experts"
            description="Strive to make the customers more beautiful and thus happier"
          />
          <FactNumber
            icon={"revenue"}
            number="3.2"
            title="Billion Euros"
            description="revenue was generated by Douglas in the 2019/20 financial year"
          />
          <FactNumber
            icon={"shop"}
            number="130,000"
            title="Beauty experts"
            description="because we care about you in online shops, and in stores"
          />
        </div>
      </div>
      <div className="text-center w-2/3 mx-auto my-20">
        <h4 className="font-krona mb-4">Imprint</h4>
        <p>Wavey Inc. Wavey-Street 7-11 40235 Waveylans</p>
        <p className="mb-4">
          You can reach us by email at: service@wavey.wavey. Our deliveries go
          out every mSunday evening so you can get them as early in the week as
          possible
        </p>
      </div>
    </>
  );
};

export default About;
